### PR TITLE
Web-Update / Timer / Status page

### PR DESCRIPTION
**Pull request by UdoRat**
Added
- Web update integrated to update the firmware without opening the divice. For that Flash size "1M (64K SPIFFS)" needs to be set
- Timer to command beeing on or off for defined seconds (to limit operation time e.g. in case of loss of control server, WiFi, etc.)
- Added some more details on the start page 
- Streamelined On and Off to remove code redundancy

### CODE REVIEW

**Comment by jamct** [comment]
Thanks for your ideas. This project is getting very complex now. I will add your code to the main program and create a second .ino-file with a basic example for all beginners to get into this topic.

**Comment by huddx01** [comment]
UdoRat, when I try to compile your patch-1 Version, I get the following errors:

`Documents/Arduino/sonoffSocket-master/sonoffSocket/sonoffSocket.ino: In lambda function:
sonoffSocket:144: error: 'Switch_On' was not declared in this scope
     Switch_On();
               ^
Arduino/sonoffSocket-master/sonoffSocket/sonoffSocket.ino: In lambda function:
sonoffSocket:150: error: 'Switch_Off' was not declared in this scope
     Switch_Off();
                ^`

What am I doing wrong?

**Comment by jamct** [comment]
@huddx01 : There is a missing } in line 205 causing compiler error.
 I will check the whole code  next week and merge UdoRats PR.

**Comment by huddx01** [comment]
@jamct : Thanks! That was the issue...

**Comment by McOrvas** [comment]
Hi jamct, I kindly want to ask, when will you merge UdoRat's PR? Thanks.

**Comment by jamct** [comment]
Thanks @UdoRat, I just fixed a typo and added a missing "server.send" when setting timer.

**Pull request merged**
